# Generate a hugo static website and upload it to bluzelle
name: Hugo-Bluzelle

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Hugo
      uses: klakegg/actions-hugo@1.0.0
      with: 
        target: site

    - name: Checkout
      uses: actions/checkout@v2
      with:
        repository: 'bluzelle/curium'
        fetch-depth: 0

    - name: Node
      uses: actions/setup-node@v2

    - name: Bluzelle
      run: |
        npm install
        npm upload-files
